//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biodanza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicio()
        {
            this.Musicas = new HashSet<Musica>();
        }
    
        public int IdEjercicio { get; set; }
        public string Nombre { get; set; }
        public int IdGrupo { get; set; }
        public string Descripcion { get; set; }
        public string Objetivo { get; set; }
        public string Observaciones { get; set; }
        public string Detalle { get; set; }
        public string Notas { get; set; }
    
        public virtual GrupoEjercicio GrupoEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musica> Musicas { get; set; }
    }
}
