//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biodanza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interprete
    {
        public string Interprete1 { get; set; }
        public string NombreCorrecto { get; set; }
    }
}
