//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biodanza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musica()
        {
            this.Ejercicios = new HashSet<Ejercicio>();
        }
    
        public int IdMusica { get; set; }
        public int IdColeccion { get; set; }
        public int NroCd { get; set; }
        public int NroPista { get; set; }
        public string Nombre { get; set; }
        public string Interprete { get; set; }
        public Nullable<bool> T { get; set; }
        public Nullable<bool> A { get; set; }
        public Nullable<bool> V { get; set; }
        public Nullable<bool> S { get; set; }
        public Nullable<bool> C { get; set; }
        public Nullable<bool> M { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public string Archivo { get; set; }
        public string Carpeta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ejercicio> Ejercicios { get; set; }
        public virtual ColeccionMusica ColeccionMusica { get; set; }
    }
}
