//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biodanza.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempMusica
    {
        public int NroCd { get; set; }
        public int NroPista { get; set; }
        public int Col { get; set; }
        public string texto { get; set; }
    }
}
